-- MySQL Script generated by MySQL Workbench
-- Mon May 31 19:03:25 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Bankdb1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Bankdb1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Bankdb1` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `Bankdb1` ;

-- -----------------------------------------------------
-- Table `Bankdb1`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bankdb1`.`Account` (
  `Account_no` INT NOT NULL,
  `FirstName` VARCHAR(45) NULL DEFAULT NULL,
  `LastName` VARCHAR(45) NULL DEFAULT NULL,
  `Balance` DECIMAL(10,0) NULL DEFAULT NULL,
  PRIMARY KEY (`Account_no`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Bankdb1`.`Transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bankdb1`.`Transaction` (
  `Transaction_id` INT NOT NULL,
  `Transaction_type` VARCHAR(45) NULL DEFAULT NULL,
  `Amount` DECIMAL(10,2) NULL DEFAULT NULL,
  `Account_no` INT NULL DEFAULT NULL,
  PRIMARY KEY (`Transaction_id`),
  INDEX `Account_no_idx` (`Account_no` ASC) VISIBLE,
  CONSTRAINT `Account_no`
    FOREIGN KEY (`Account_no`)
    REFERENCES `Bankdb1`.`Account` (`Account_no`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Bankdb1`.`Transfer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bankdb1`.`Transfer` (
  `Transfer_id` INT NOT NULL,
  `From_Account` INT NULL DEFAULT NULL,
  `To_Account` INT NULL DEFAULT NULL,
  `Amount` VARCHAR(45) NULL DEFAULT NULL,
  `Reason` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Transfer_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
