-- MySQL Script generated by MySQL Workbench
-- Sun Jun 13 02:47:32 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bank_System
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bank_System
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bank_System` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bank_System` ;

-- -----------------------------------------------------
-- Table `bank_System`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank_System`.`account` (
  `account_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `balance` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`account_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bank_System`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank_System`.`transaction` (
  `transaction_id` INT NOT NULL,
  `transaction_type` VARCHAR(45) NULL DEFAULT NULL,
  `amount` DECIMAL(10,2) NULL DEFAULT NULL,
  `account_no` INT NULL DEFAULT NULL,
  PRIMARY KEY (`transaction_id`),
  INDEX `account_no_idx` (`account_no` ASC) VISIBLE,
  CONSTRAINT `account_no`
    FOREIGN KEY (`account_no`)
    REFERENCES `bank_System`.`account` (`account_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
